


MODULE_LIBS =   \
          ./libs/Config.o \
          ./libs/InsideNet.o \
          ./libs/main.o \
          ./libs/QuickStartManager.o \
          ./libs/RoomManager.o \
          ./libs/UserManager.o \
          ./libs/Work.o \
         




MODULE_SRC =     \
          ./Config.o \
          ./InsideNet.o \
          ./main.o \
          ./QuickStartManager.o \
          ./RoomManager.o \
          ./UserManager.o \
          ./Work.o \
        
